import React from 'react';

const Ai2html = ({ base, graphic }) => {
  let updatedBase = base;

  let ai2html = {
    anatomy: `
      <!-- Generated by ai2html v0.120.0 - 2026-03-06 10:25 -->
        <!-- ai file: anatomy.ai -->
        <style media="screen,print">
          #g-anatomy-box,
          #g-anatomy-box .g-artboard {
            margin: 0 auto;
          }
          #g-anatomy-box p {
            margin: 0;
          }
          #g-anatomy-box .g-aiAbs {
            position: absolute;
          }
          #g-anatomy-box .g-aiImg {
            position: absolute;
            top: 0;
            display: block;
            width: 100% !important;
          }
          #g-anatomy-box .g-aiSymbol {
            position: absolute;
            box-sizing: border-box;
          }
          #g-anatomy-box .g-aiPointText p {
            white-space: nowrap;
          }
          #g-anatomy-mobile {
            position: relative;
            overflow: hidden;
          }
          @media (min-width: 640px) {
            #g-anatomy-mobile {
              display: none;
            }
          }
          #g-anatomy-mobile p {
            font-family: Helvetica;
            font-weight: 500;
            line-height: 20px;
            opacity: 1;
            letter-spacing: 0em;
            font-size: 18px;
            text-align: left;
            color: rgb(0, 0, 0);
            text-transform: none;
            padding-bottom: 0;
            padding-top: 0;
            mix-blend-mode: normal;
            font-style: normal;
            height: auto;
            position: static;
          }
          #g-anatomy-mobile .g-pstyle0 {
            text-align: right;
          }
          #g-anatomy-text-well {
            position: relative;
            overflow: hidden;
          }
          #g-anatomy-text-well p {
            font-family: Helvetica;
            font-weight: 500;
            line-height: 20px;
            opacity: 1;
            letter-spacing: 0em;
            font-size: 18px;
            text-align: left;
            color: rgb(0, 0, 0);
            text-transform: none;
            padding-bottom: 0;
            padding-top: 0;
            mix-blend-mode: normal;
            font-style: normal;
            height: auto;
            position: static;
          }
          #g-anatomy-text-well .g-pstyle0 {
            text-align: right;
          }
            @media (max-width: 639px) {
            #g-anatomy-text-well {
              display: none;
            }
          }
        </style>

        <div id="g-anatomy-box" class="ai2html">
          <!-- Artboard: mobile -->
          <div
            id="g-anatomy-mobile"
            class="g-artboard"
            style="max-width: 320px; max-height: 550px"
            data-aspect-ratio="0.582"
            data-min-width="0"
            data-max-width="639">
            <div style="padding: 0 0 171.875% 0"></div>
            <img
              id="g-anatomy-mobile-img"
              class="g-anatomy-mobile-img g-aiImg"
              alt=""
              src="${updatedBase}assets/anatomy-mobile.jpg" />
            <div
              id="g-ai0-1"
              class="g-Layer_1 g-aiAbs"
              style="top: 1.0909%; left: 4.5313%; width: 24.375%">
              <p>Headline</p>
            </div>
            <div
              id="g-ai0-2"
              class="g-Layer_1 g-aiAbs"
              style="top: 1.0909%; left: 48.7568%; width: 44.375%">
              <p>Deck, precede,</p>
              <p>intro, chatter, subhead</p>
            </div>
            <div
              id="g-ai0-3"
              class="g-Layer_1 g-aiAbs"
              style="top: 22.3636%; right: 0.9375%; width: 27.1875%">
              <p class="g-pstyle0">Key, legend</p>
            </div>
            <div
              id="g-ai0-4"
              class="g-Layer_1 g-aiAbs"
              style="top: 33.6364%; right: 0.9307%; width: 18.125%">
              <p class="g-pstyle0">Values</p>
              <p class="g-pstyle0">and axis</p>
            </div>
            <div
              id="g-ai0-5"
              class="g-Layer_1 g-aiAbs"
              style="top: 52.9091%; right: 0.9375%; width: 28.75%">
              <p class="g-pstyle0">Categories</p>
            </div>
            <div
              id="g-ai0-6"
              class="g-Layer_1 g-aiAbs"
              style="top: 66.1818%; right: 0.9375%; width: 27.1875%">
              <p class="g-pstyle0">Annotation</p>
            </div>
            <div
              id="g-ai0-7"
              class="g-Layer_1 g-aiAbs"
              style="top: 76.7273%; left: 2.5068%; width: 25.3125%">
              <p>Note(s)</p>
            </div>
            <div
              id="g-ai0-8"
              class="g-Layer_1 g-aiAbs"
              style="top: 95.0909%; left: 4.0693%; width: 61.25%">
              <p>Source(s) and credit(s)</p>
            </div>
          </div>

          <!-- Artboard: text-well -->
          <div
            id="g-anatomy-text-well"
            class="g-artboard"
            style="width: 640px; height: 395px"
            data-aspect-ratio="1.62"
            data-min-width="640">
            <div style=""></div>
            <img
              id="g-anatomy-text-well-img"
              class="g-anatomy-text-well-img g-aiImg"
              alt=""
              src="${updatedBase}assets/anatomy-text-well.jpg" />
            <div
              id="g-ai1-1"
              class="g-Layer_1 g-aiAbs"
              style="top: 1.519%; left: 0.3159%; width: 12.6563%">
              <p>Deck,</p>
              <p>precede,</p>
              <p>intro,</p>
              <p>chatter,</p>
              <p>subhead</p>
            </div>
            <div
              id="g-ai1-2"
              class="g-Layer_1 g-aiAbs"
              style="top: 1.519%; left: 23.9844%; width: 12.1875%">
              <p>Headline</p>
            </div>
            <div
              id="g-ai1-3"
              class="g-Layer_1 g-aiAbs"
              style="top: 1.519%; right: 0.4688%; width: 13.5937%">
              <p class="g-pstyle0">Annotation</p>
            </div>
            <div
              id="g-ai1-4"
              class="g-Layer_1 g-aiAbs"
              style="top: 29.6203%; left: 0.3159%; width: 12.6563%">
              <p>Units</p>
            </div>
            <div
              id="g-ai1-5"
              class="g-Layer_1 g-aiAbs"
              style="top: 41.519%; right: 0.4688%; width: 13.5937%">
              <p class="g-pstyle0">Key, legend</p>
            </div>
            <div
              id="g-ai1-6"
              class="g-Layer_1 g-aiAbs"
              style="top: 60%; left: 0.3159%; width: 9.0625%">
              <p>Values</p>
              <p>and axis</p>
            </div>
            <div
              id="g-ai1-7"
              class="g-Layer_1 g-aiAbs"
              style="top: 85.3165%; right: 0.4688%; width: 14.375%">
              <p class="g-pstyle0">Categories</p>
            </div>
            <div
              id="g-ai1-8"
              class="g-Layer_1 g-aiAbs"
              style="top: 88.6076%; left: 0.3159%; width: 12.6563%">
              <p>Note(s)</p>
            </div>
            <div
              id="g-ai1-9"
              class="g-Layer_1 g-aiAbs"
              style="top: 92.4051%; right: 0.4688%; width: 14.375%">
              <p class="g-pstyle0">Credit</p>
            </div>
            <div
              id="g-ai1-10"
              class="g-Layer_1 g-aiAbs"
              style="top: 93.4177%; left: 0.3159%; width: 12.6563%">
              <p>Source(s)</p>
            </div>
          </div>
        </div>

        <!-- End ai2html - 2026-03-06 10:25 -->
    `,
  };

  return (
    <figure
      className='mt-md mb-lg'
      dangerouslySetInnerHTML={{ __html: ai2html[graphic] }}
    />
  );
};

export default Ai2html;
